package com.example.m203

data class Country(
    val iso : String,
    val name : String,
    val imageId : Int
)

val countries = listOf(
    Country("aw","آروبا",R.drawable.aw),
    Country("az","أذربيجان",R.drawable.az),
    Country("am","أرمينيا",R.drawable.am),
    Country("es","أسبانيا",R.drawable.es),
    Country("au","أستراليا",R.drawable.au),
    Country("af","أفغانستان",R.drawable.af),
    Country("al","ألبانيا",R.drawable.al),
    Country("de","ألمانيا",R.drawable.de),
    Country("ag","أنتيجوا وبربودا",R.drawable.ag),
    Country("ao","أنجولا",R.drawable.ao),
    Country("ai","أنجويلا",R.drawable.ai),
    Country("ad","أندورا",R.drawable.ad),
    Country("uy","أورجواي",R.drawable.uy),
    Country("uz","أوزبكستان",R.drawable.uz),
    Country("ug","أوغندا",R.drawable.ug),
    Country("ua","أوكرانيا",R.drawable.ua),
    Country("ie","أيرلندا",R.drawable.ie),
    Country("et","اثيوبيا",R.drawable.et),
    Country("er","اريتريا",R.drawable.er),
    Country("ee","استونيا",R.drawable.ee),
    Country("il","اسرائيل",R.drawable.il),
    Country("ar","الأرجنتين",R.drawable.ar),
    Country("jo","الأردن",R.drawable.jo),
    Country("ec","الاكوادور",R.drawable.ec),
    Country("ae","الامارات العربية المتحدة",R.drawable.ae),
    Country("bs","الباهاما",R.drawable.bs),
    Country("bh","البحرين",R.drawable.bh),
    Country("br","البرازيل",R.drawable.br),
    Country("pt","البرتغال",R.drawable.pt),
    Country("ba","البوسنة والهرسك",R.drawable.ba),
    Country("ga","الجابون",R.drawable.ga),
    Country("me","الجبل الأسود",R.drawable.me),
    Country("dz","الجزائر",R.drawable.dz),
    Country("dk","الدانمرك",R.drawable.dk),
    Country("cv","الرأس الأخضر",R.drawable.cv),
    Country("sv","السلفادور",R.drawable.sv),
    Country("sn","السنغال",R.drawable.sn),
    Country("sd","السودان",R.drawable.sd),
    Country("se","السويد",R.drawable.se),
    Country("eh","الصحراء الغربية",R.drawable.eh),
    Country("so","الصومال",R.drawable.so),
    Country("cn","الصين",R.drawable.cn),
    Country("iq","العراق",R.drawable.iq),
    Country("va","الفاتيكان",R.drawable.va),
    Country("ph","الفيلبين",R.drawable.ph),
    Country("aq","القطب الجنوبي",R.drawable.aq),
    Country("cm","الكاميرون",R.drawable.cm),
    Country("cg","الكونغو - برازافيل",R.drawable.cg),
    Country("kw","الكويت",R.drawable.kw),
    Country("hu","المجر",R.drawable.hu),
    Country("io","المحيط الهندي البريطاني",R.drawable.io),
    Country("ma","المغرب",R.drawable.ma),
    Country("tf","المقاطعات الجنوبية الفرنسية",R.drawable.tf),
    Country("mx","المكسيك",R.drawable.mx),
    Country("sa","المملكة العربية السعودية",R.drawable.sa),
    Country("gb","المملكة المتحدة",R.drawable.gb),
    Country("no","النرويج",R.drawable.no),
    Country("at","النمسا",R.drawable.at),
    Country("ne","النيجر",R.drawable.ne),
    Country("us","الولايات المتحدة الأمريكية",R.drawable.us),
    Country("jp","اليابان",R.drawable.jp),
    Country("ye","اليمن",R.drawable.ye),
    Country("gr","اليونان",R.drawable.gr),
    Country("id","اندونيسيا",R.drawable.id),
    Country("ir","ايران",R.drawable.ir),
    Country("it","ايطاليا",R.drawable.it),
    Country("pg","بابوا غينيا الجديدة",R.drawable.pg),
    Country("py","باراجواي",R.drawable.py),
    Country("pk","باكستان",R.drawable.pk),
    Country("pw","بالاو",R.drawable.pw),
    Country("bw","بتسوانا",R.drawable.bw),
    Country("pn","بتكايرن",R.drawable.pn),
    Country("bb","بربادوس",R.drawable.bb),
    Country("bm","برمودا",R.drawable.bm),
    Country("bn","بروناي",R.drawable.bn),
    Country("be","بلجيكا",R.drawable.be),
    Country("bg","بلغاريا",R.drawable.bg),
    Country("bz","بليز",R.drawable.bz),
    Country("bd","بنجلاديش",R.drawable.bd),
    Country("pa","بنما",R.drawable.pa),
    Country("bj","بنين",R.drawable.bj),
    Country("bt","بوتان",R.drawable.bt),
    Country("pr","بورتوريكو",R.drawable.pr),
    Country("bf","بوركينا فاسو",R.drawable.bf),
    Country("bi","بوروندي",R.drawable.bi),
    Country("pl","بولندا",R.drawable.pl),
    Country("bo","بوليفيا",R.drawable.bo),
    Country("pf","بولينيزيا الفرنسية",R.drawable.pf),
    Country("pe","بيرو",R.drawable.pe),
    Country("tz","تانزانيا",R.drawable.tz),
    Country("th","تايلند",R.drawable.th),
    Country("tw","تايوان",R.drawable.tw),
    Country("tm","تركمانستان",R.drawable.tm),
    Country("tr","تركيا",R.drawable.tr),
    Country("tt","ترينيداد وتوباغو",R.drawable.tt),
    Country("td","تشاد",R.drawable.td),
    Country("tg","توجو",R.drawable.tg),
    Country("tv","توفالو",R.drawable.tv),
    Country("tk","توكيلو",R.drawable.tk),
    Country("to","تونجا",R.drawable.to),
    Country("tn","تونس",R.drawable.tn),
    Country("tl","تيمور الشرقية",R.drawable.tl),
    Country("jm","جامايكا",R.drawable.jm),
    Country("gi","جبل طارق",R.drawable.gi),
    Country("gd","جرينادا",R.drawable.gd),
    Country("gl","جرينلاند",R.drawable.gl),
    Country("ax","جزر أولان",R.drawable.ax),
    Country("tc","جزر الترك وجايكوس",R.drawable.tc),
    Country("km","جزر القمر",R.drawable.km),
    Country("ky","جزر الكايمن",R.drawable.ky),
    Country("mh","جزر المارشال",R.drawable.mh),
    Country("mv","جزر الملديف",R.drawable.mv),
    Country("um","جزر الولايات المتحدة البعيدة الصغيرة",R.drawable.um),
    Country("sb","جزر سليمان",R.drawable.sb),
    Country("fo","جزر فارو",R.drawable.fo),
    Country("vi","جزر فرجين الأمريكية",R.drawable.vi),
    Country("vg","جزر فرجين البريطانية",R.drawable.vg),
    Country("fk","جزر فوكلاند",R.drawable.fk),
    Country("ck","جزر كوك",R.drawable.ck),
    Country("cc","جزر كوكوس",R.drawable.cc),
    Country("mp","جزر ماريانا الشمالية",R.drawable.mp),
    Country("wf","جزر والس وفوتونا",R.drawable.wf),
    Country("cx","جزيرة الكريسماس",R.drawable.cx),
    Country("bv","جزيرة بوفيه",R.drawable.bv),
    Country("im","جزيرة مان",R.drawable.im),
    Country("nf","جزيرة نورفوك",R.drawable.nf),
    Country("hm","جزيرة هيرد وماكدونالد",R.drawable.hm),
    Country("cf","جمهورية افريقيا الوسطى",R.drawable.cf),
    Country("cz","جمهورية التشيك",R.drawable.cz),
    Country("cd","جمهورية الكونغو الديمقراطية",R.drawable.cd),
    Country("za","جمهورية جنوب افريقيا",R.drawable.za),
    Country("gt","جواتيمالا",R.drawable.gt),
    Country("gp","جوادلوب",R.drawable.gp),
    Country("gu","جوام",R.drawable.gu),
    Country("ge","جورجيا",R.drawable.ge),
    Country("gs","جورجيا الجنوبية وجزر ساندويتش الجنوبية",R.drawable.gs),
    Country("dj","جيبوتي",R.drawable.dj),
    Country("je","جيرسي",R.drawable.je),
    Country("dm","دومينيكا",R.drawable.dm),
    Country("rw","رواندا",R.drawable.rw),
    Country("ru","روسيا",R.drawable.ru),
    Country("by","روسيا البيضاء",R.drawable.by),
    Country("ro","رومانيا",R.drawable.ro),
    Country("re","روينيون",R.drawable.re),
    Country("zm","زامبيا",R.drawable.zm),
    Country("zw","زيمبابوي",R.drawable.zw),
    Country("ci","ساحل العاج",R.drawable.ci),
    Country("ws","ساموا",R.drawable.ws),
    Country("sm","سان مارينو",R.drawable.sm),
    Country("pm","سانت بيير وميكولون",R.drawable.pm),
    Country("vc","سانت فنسنت وغرنادين",R.drawable.vc),
    Country("kn","سانت كيتس ونيفيس",R.drawable.kn),
    Country("lc","سانت لوسيا",R.drawable.lc),
    Country("mf","سانت مارتين",R.drawable.mf),
    Country("sh","سانت هيلنا",R.drawable.sh),
    Country("st","ساو تومي وبرينسيبي",R.drawable.st),
    Country("lk","سريلانكا",R.drawable.lk),
    Country("sj","سفالبارد وجان مايان",R.drawable.sj),
    Country("sk","سلوفاكيا",R.drawable.sk),
    Country("si","سلوفينيا",R.drawable.si),
    Country("sg","سنغافورة",R.drawable.sg),
    Country("sz","سوازيلاند",R.drawable.sz),
    Country("sy","سوريا",R.drawable.sy),
    Country("sr","سورينام",R.drawable.sr),
    Country("ch","سويسرا",R.drawable.ch),
    Country("sl","سيراليون",R.drawable.sl),
    Country("sc","سيشل",R.drawable.sc),
    Country("cl","شيلي",R.drawable.cl),
    Country("rs","صربيا",R.drawable.rs),
    Country("tj","طاجكستان",R.drawable.tj),
    Country("om","عمان",R.drawable.om),
    Country("gm","غامبيا",R.drawable.gm),
    Country("gh","غانا",R.drawable.gh),
    Country("gf","غويانا",R.drawable.gf),
    Country("gy","غيانا",R.drawable.gy),
    Country("gn","غينيا",R.drawable.gn),
    Country("gq","غينيا الاستوائية",R.drawable.gq),
    Country("gw","غينيا بيساو",R.drawable.gw),
    Country("vu","فانواتو",R.drawable.vu),
    Country("fr","فرنسا",R.drawable.fr),
    Country("ps","فلسطين",R.drawable.ps),
    Country("ve","فنزويلا",R.drawable.ve),
    Country("fi","فنلندا",R.drawable.fi),
    Country("vn","فيتنام",R.drawable.vn),
    Country("fj","فيجي",R.drawable.fj),
    Country("cy","قبرص",R.drawable.cy),
    Country("kg","قرغيزستان",R.drawable.kg),
    Country("qa","قطر",R.drawable.qa),
    Country("kz","كازاخستان",R.drawable.kz),
    Country("nc","كاليدونيا الجديدة",R.drawable.nc),
    Country("hr","كرواتيا",R.drawable.hr),
    Country("kh","كمبوديا",R.drawable.kh),
    Country("ca","كندا",R.drawable.ca),
    Country("cu","كوبا",R.drawable.cu),
    Country("kr","كوريا الجنوبية",R.drawable.kr),
    Country("kp","كوريا الشمالية",R.drawable.kp),
    Country("cr","كوستاريكا",R.drawable.cr),
    Country("co","كولومبيا",R.drawable.co),
    Country("ki","كيريباتي",R.drawable.ki),
    Country("ke","كينيا",R.drawable.ke),
    Country("lv","لاتفيا",R.drawable.lv),
    Country("la","لاوس",R.drawable.la),
    Country("lb","لبنان",R.drawable.lb),
    Country("lu","لوكسمبورج",R.drawable.lu),
    Country("ly","ليبيا",R.drawable.ly),
    Country("lr","ليبيريا",R.drawable.lr),
    Country("lt","ليتوانيا",R.drawable.lt),
    Country("li","ليختنشتاين",R.drawable.li),
    Country("ls","ليسوتو",R.drawable.ls),
    Country("mq","مارتينيك",R.drawable.mq),
    Country("mo","ماكاو الصينية",R.drawable.mo),
    Country("mt","مالطا",R.drawable.mt),
    Country("ml","مالي",R.drawable.ml),
    Country("my","ماليزيا",R.drawable.my),
    Country("yt","مايوت",R.drawable.yt),
    Country("mg","مدغشقر",R.drawable.mg),
    Country("eg","مصر",R.drawable.eg),
    Country("mk","مقدونيا",R.drawable.mk),
    Country("mw","ملاوي",R.drawable.mw),
    Country("mn","منغوليا",R.drawable.mn),
    Country("mr","موريتانيا",R.drawable.mr),
    Country("mu","موريشيوس",R.drawable.mu),
    Country("mz","موزمبيق",R.drawable.mz),
    Country("md","مولدافيا",R.drawable.md),
    Country("mc","موناكو",R.drawable.mc),
    Country("ms","مونتسرات",R.drawable.ms),
    Country("mm","ميانمار",R.drawable.mm),
    Country("fm","ميكرونيزيا",R.drawable.fm),
    Country("na","ناميبيا",R.drawable.na),
    Country("nr","نورو",R.drawable.nr),
    Country("np","نيبال",R.drawable.np),
    Country("ng","نيجيريا",R.drawable.ng),
    Country("ni","نيكاراجوا",R.drawable.ni),
    Country("nz","نيوزيلاندا",R.drawable.nz),
    Country("nu","نيوي",R.drawable.nu),
    Country("ht","هايتي",R.drawable.ht),
    Country("hn","هندوراس",R.drawable.hn),
    Country("nl","هولندا",R.drawable.nl),
    Country("hk","هونج كونج الصينية",R.drawable.hk),
    Country("ss","جنوب السودان",R.drawable.ss),
    Country("xk","كوسوفو",R.drawable.xk),

    )