package com.example.m203

data class Country(
    val iso : String,
    val name : String,
    val imageId : Int,
    val capital : String
)

val countries = listOf(
    Country("aw","آروبا",R.drawable.aw,"أورانجستاد"),
    Country("az","أذربيجان",R.drawable.az,"باكو"),
    Country("am","أرمينيا",R.drawable.am,"يريفان"),
    Country("es","أسبانيا",R.drawable.es,"مدريد"),
    Country("au","أستراليا",R.drawable.au,"كانبيرا"),
    Country("af","أفغانستان",R.drawable.af,"كابول"),
    Country("al","ألبانيا",R.drawable.al,"تيرانا"),
    Country("de","ألمانيا",R.drawable.de,"برلين"),
    Country("ag","أنتيجوا وبربودا",R.drawable.ag,"سانت جونز"),
    Country("ao","أنجولا",R.drawable.ao,"لواندا"),
    Country("ai","أنجويلا",R.drawable.ai,"ذا فالي"),
    Country("ad","أندورا",R.drawable.ad,"أندورا لا فيلا"),
    Country("uy","أورجواي",R.drawable.uy,"مونتيفيديو"),
    Country("uz","أوزبكستان",R.drawable.uz,"طشقند"),
    Country("ug","أوغندا",R.drawable.ug,"كمبالا"),
    Country("ua","أوكرانيا",R.drawable.ua,"كييف"),
    Country("ie","أيرلندا",R.drawable.ie,"دبلن"),
    Country("et","اثيوبيا",R.drawable.et,"أديس أبابا"),
    Country("er","اريتريا",R.drawable.er,"أسمرة"),
    Country("ee","استونيا",R.drawable.ee,"تالين"),
    Country("il","اسرائيل",R.drawable.il,"القدس"),
    Country("ar","الأرجنتين",R.drawable.ar,"بوينس آيرس"),
    Country("jo","الأردن",R.drawable.jo,"عمان"),
    Country("ec","الاكوادور",R.drawable.ec,"كيتو"),
    Country("ae","الامارات العربية المتحدة",R.drawable.ae,"أبو ظبي"),
    Country("bs","الباهاما",R.drawable.bs,"ناساو"),
    Country("bh","البحرين",R.drawable.bh,"المنامة"),
    Country("br","البرازيل",R.drawable.br,"برازيليا"),
    Country("pt","البرتغال",R.drawable.pt,"لشبونة"),
    Country("ba","البوسنة والهرسك",R.drawable.ba,"سراييفو"),
    Country("ga","الجابون",R.drawable.ga,"ليبروفيل"),
    Country("me","الجبل الأسود",R.drawable.me,"بودغوريتسا"),
    Country("dz","الجزائر",R.drawable.dz,"الجزائر"),
    Country("dk","الدانمرك",R.drawable.dk,"كوبنهاغن"),
    Country("cv","الرأس الأخضر",R.drawable.cv,"برايا"),
    Country("sv","السلفادور",R.drawable.sv,"سان سالفادور"),
    Country("sn","السنغال",R.drawable.sn,"داكار"),
    Country("sd","السودان",R.drawable.sd,"الخرطوم"),
    Country("se","السويد",R.drawable.se,"ستوكهولم"),
    Country("so","الصومال",R.drawable.so,"مقديشو"),
    Country("cn","الصين",R.drawable.cn,"بكين"),
    Country("iq","العراق",R.drawable.iq,"بغداد"),
    Country("va","الفاتيكان",R.drawable.va,"الفاتيكان"),
    Country("ph","الفيلبين",R.drawable.ph,"مانيلا"),
    Country("aq","القطب الجنوبي",R.drawable.aq,"بدون عاصمة"),
    Country("cm","الكاميرون",R.drawable.cm,"ياوندي"),
    Country("cg","الكونغو - برازافيل",R.drawable.cg,"برازافيل"),
    Country("kw","الكويت",R.drawable.kw,"مدينة الكويت"),
    Country("hu","المجر",R.drawable.hu,"بودابست"),
    Country("io","المحيط الهندي البريطاني",R.drawable.io,"دييغو غارسيا"),
    Country("ma","المغرب",R.drawable.ma,"الرباط"),
    Country("tf","المقاطعات الجنوبية الفرنسية",R.drawable.tf,"بدون عاصمة"),
    Country("mx","المكسيك",R.drawable.mx,"مكسيكو سيتي"),
    Country("sa","المملكة العربية السعودية",R.drawable.sa,"الرياض"),
    Country("gb","المملكة المتحدة",R.drawable.gb,"لندن"),
    Country("no","النرويج",R.drawable.no,"أوسلو"),
    Country("at","النمسا",R.drawable.at,"فيينا"),
    Country("ne","النيجر",R.drawable.ne,"نيامي"),
    Country("us","الولايات المتحدة الأمريكية",R.drawable.us,"واشنطن العاصمة"),
    Country("jp","اليابان",R.drawable.jp,"طوكيو"),
    Country("ye","اليمن",R.drawable.ye,"صنعاء"),
    Country("gr","اليونان",R.drawable.gr,"أثينا"),
    Country("id","اندونيسيا",R.drawable.id,"جاكرتا"),
    Country("ir","ايران",R.drawable.ir,"طهران"),
    Country("it","ايطاليا",R.drawable.it,"روما"),
    Country("pg","بابوا غينيا الجديدة",R.drawable.pg,"بورت موريسبي"),
    Country("py","باراجواي",R.drawable.py,"أسونسيون"),
    Country("pk","باكستان",R.drawable.pk,"إسلام أباد"),
    Country("pw","بالاو",R.drawable.pw,"نجيرولمود"),
    Country("bw","بتسوانا",R.drawable.bw,"غابورون"),
    Country("pn","بتكايرن",R.drawable.pn,"آدامستاون"),
    Country("bb","بربادوس",R.drawable.bb,"بريدجتاون"),
    Country("bm","برمودا",R.drawable.bm,"هاملتون"),
    Country("bn","بروناي",R.drawable.bn,"بنادر سري بيجَاوَن"),
    Country("be","بلجيكا",R.drawable.be,"بروكسل"),
    Country("bg","بلغاريا",R.drawable.bg,"صوفيا"),
    Country("bz","بليز",R.drawable.bz,"بلموبان"),
    Country("bd","بنجلاديش",R.drawable.bd,"داكا"),
    Country("pa","بنما",R.drawable.pa,"بنما"),
    Country("bj","بنين",R.drawable.bj,"بورتو نوفو"),
    Country("bt","بوتان",R.drawable.bt,"تيمفو"),
    Country("pr","بورتوريكو",R.drawable.pr,"سان خوان"),
    Country("bf","بوركينا فاسو",R.drawable.bf,"واجادوغو"),
    Country("bi","بوروندي",R.drawable.bi,"غيتيغا"),
    Country("pl","بولندا",R.drawable.pl,"وارسو"),
    Country("bo","بوليفيا",R.drawable.bo,"سوكري"),
    Country("pf","بولينيزيا الفرنسية",R.drawable.pf,"بابيتي"),
    Country("pe","بيرو",R.drawable.pe,"ليما"),
    Country("tz","تانزانيا",R.drawable.tz,"دودوما"),
    Country("th","تايلند",R.drawable.th,"بانكوك"),
    Country("tw","تايوان",R.drawable.tw,"تايبيه"),
    Country("tm","تركمانستان",R.drawable.tm,"عشق آباد"),
    Country("tr","تركيا",R.drawable.tr,"أنقرة"),
    Country("tt","ترينيداد وتوباغو",R.drawable.tt,"بورت أوف سبين"),
    Country("td","تشاد",R.drawable.td,"نجامينا"),
    Country("tg","توجو",R.drawable.tg,"لومه"),
    Country("tv","توفالو",R.drawable.tv,"فونافوتي"),
    Country("tk","توكيلو",R.drawable.tk,"آتافو"),
    Country("to","تونجا",R.drawable.to,"نوكوالوفا"),
    Country("tn","تونس",R.drawable.tn,"تونس"),
    Country("tl","تيمور الشرقية",R.drawable.tl,"ديلّي"),
    Country("jm","جامايكا",R.drawable.jm,"كينغستون"),
    Country("gi","جبل طارق",R.drawable.gi,"جبل طارق"),
    Country("gd","جرينادا",R.drawable.gd,"سانت جورج"),
    Country("gl","جرينلاند",R.drawable.gl,"نوك"),
    Country("ax","جزر أولان",R.drawable.ax,"ماريهامن"),
    Country("tc","جزر الترك وجايكوس",R.drawable.tc,"كوكبورن تاون"),
    Country("km","جزر القمر",R.drawable.km,"موروني"),
    Country("ky","جزر الكايمن",R.drawable.ky,"جورج تاون"),
    Country("mh","جزر المارشال",R.drawable.mh,"مادجورو"),
    Country("mv","جزر الملديف",R.drawable.mv,"ماليه"),
    Country("um","جزر الولايات المتحدة البعيدة الصغيرة",R.drawable.um,"بدون عاصمة"),
    Country("sb","جزر سليمان",R.drawable.sb,"هونيارا"),
    Country("fo","جزر فارو",R.drawable.fo,"تورشافن"),
    Country("vi","جزر فرجين الأمريكية",R.drawable.vi,"شارلوت أماليا"),
    Country("vg","جزر فرجين البريطانية",R.drawable.vg,"رود تاون"),
    Country("fk","جزر فوكلاند",R.drawable.fk,"ستانلي"),
    Country("ck","جزر كوك",R.drawable.ck,"أفاروآ"),
    Country("cc","جزر كوكوس",R.drawable.cc,"ويست آيلاند"),
    Country("mp","جزر ماريانا الشمالية",R.drawable.mp,"سايبان"),
    Country("wf","جزر والس وفوتونا",R.drawable.wf,"ماتا أوتو"),
    Country("cx","جزيرة الكريسماس",R.drawable.cx,"فلاينغ فيش كوف"),
    Country("bv","جزيرة بوفيه",R.drawable.bv,"بدون عاصمة"),
    Country("im","جزيرة مان",R.drawable.im,"دوغلاس"),
    Country("nf","جزيرة نورفوك",R.drawable.nf,"كينغستون"),
    Country("hm","جزيرة هيرد وماكدونالد",R.drawable.hm,"بدون عاصمة"),
    Country("cf","جمهورية افريقيا الوسطى",R.drawable.cf,"بانغي"),
    Country("cz","جمهورية التشيك",R.drawable.cz,"براغ"),
    Country("cd","جمهورية الكونغو الديمقراطية",R.drawable.cd,"كينشاسا"),
    Country("za","جمهورية جنوب افريقيا",R.drawable.za,"بريتوريا"),
    Country("gt","جواتيمالا",R.drawable.gt,"مدينة غواتيمالا"),
    Country("gp","جوادلوب",R.drawable.gp,"باس-تير"),
    Country("gu","جوام",R.drawable.gu,"هاغاتنا"),
    Country("ge","جورجيا",R.drawable.ge,"تبليسي"),
    Country("gs","جورجيا الجنوبية وجزر ساندويتش الجنوبية",R.drawable.gs,"بدون عاصمة"),
    Country("dj","جيبوتي",R.drawable.dj,"مدينة جيبوتي"),
    Country("je","جيرسي",R.drawable.je,"سانت هيليير"),
    Country("dm","دومينيكا",R.drawable.dm,"روزو"),
    Country("rw","رواندا",R.drawable.rw,"كيغالي"),
    Country("ru","روسيا",R.drawable.ru,"موسكو"),
    Country("by","روسيا البيضاء",R.drawable.by,"مينسك"),
    Country("ro","رومانيا",R.drawable.ro,"بوخارست"),
    Country("re","روينيون",R.drawable.re,"سان دوني"),
    Country("zm","زامبيا",R.drawable.zm,"لوساكا"),
    Country("zw","زيمبابوي",R.drawable.zw,"هراري"),
    Country("ci","ساحل العاج",R.drawable.ci,"ياموسوكرو"),
    Country("ws","ساموا",R.drawable.ws,"آبيا"),
    Country("sm","سان مارينو",R.drawable.sm,"سان مارينو"),
    Country("pm","سانت بيير وميكولون",R.drawable.pm,"سانت بيير"),
    Country("vc","سانت فنسنت وغرنادين",R.drawable.vc,"كينغستاون"),
    Country("kn","سانت كيتس ونيفيس",R.drawable.kn,"باسيتير"),
    Country("lc","سانت لوسيا",R.drawable.lc,"كاستريس"),
    Country("mf","سانت مارتين",R.drawable.mf,"ماريغو"),
    Country("sh","سانت هيلنا",R.drawable.sh,"جيمزتاون"),
    Country("st","ساو تومي وبرينسيبي",R.drawable.st,"ساو تومي"),
    Country("lk","سريلانكا",R.drawable.lk,"كولومبو"),
    Country("sj","سفالبارد وجان مايان",R.drawable.sj,"لونجياربين"),
    Country("sk","سلوفاكيا",R.drawable.sk,"براتيسلافا"),
    Country("si","سلوفينيا",R.drawable.si,"ليوبليانا"),
    Country("sg","سنغافورة",R.drawable.sg,"سنغافورة"),
    Country("sz","سوازيلاند",R.drawable.sz,"مباباني"),
    Country("sy","سوريا",R.drawable.sy,"دمشق"),
    Country("sr","سورينام",R.drawable.sr,"باراماريبو"),
    Country("ch","سويسرا",R.drawable.ch,"برن"),
    Country("sl","سيراليون",R.drawable.sl,"فريتاون"),
    Country("sc","سيشل",R.drawable.sc,"فيكتوريا"),
    Country("cl","شيلي",R.drawable.cl,"سانتياغو"),
    Country("rs","صربيا",R.drawable.rs,"بلغراد"),
    Country("tj","طاجكستان",R.drawable.tj,"دوشنبه"),
    Country("om","عمان",R.drawable.om,"مسقط"),
    Country("gm","غامبيا",R.drawable.gm,"بانجول"),
    Country("gh","غانا",R.drawable.gh,"أكرا"),
    Country("gf","غويانا",R.drawable.gf,"كاين"),
    Country("gy","غيانا",R.drawable.gy,"جورج تاون"),
    Country("gn","غينيا",R.drawable.gn,"كوناكري"),
    Country("gq","غينيا الاستوائية",R.drawable.gq,"مالابو"),
    Country("gw","غينيا بيساو",R.drawable.gw,"بيساو"),
    Country("vu","فانواتو",R.drawable.vu,"بورت فيلا"),
    Country("fr","فرنسا",R.drawable.fr,"باريس"),
    Country("ps","فلسطين",R.drawable.ps,"رام الله"),
    Country("ve","فنزويلا",R.drawable.ve,"كاراكاس"),
    Country("fi","فنلندا",R.drawable.fi,"هلسنكي"),
    Country("vn","فيتنام",R.drawable.vn,"هانوي"),
    Country("fj","فيجي",R.drawable.fj,"سوفا"),
    Country("cy","قبرص",R.drawable.cy,"نيقوسيا"),
    Country("kg","قرغيزستان",R.drawable.kg,"بيشكيك"),
    Country("qa","قطر",R.drawable.qa,"الدوحة"),
    Country("kz","كازاخستان",R.drawable.kz,"نور سلطان"),
    Country("nc","كاليدونيا الجديدة",R.drawable.nc,"نومييا"),
    Country("hr","كرواتيا",R.drawable.hr,"زغرب"),
    Country("kh","كمبوديا",R.drawable.kh,"بنوم بنه"),
    Country("ca","كندا",R.drawable.ca,"أوتاوا"),
    Country("cu","كوبا",R.drawable.cu,"هافانا"),
    Country("kr","كوريا الجنوبية",R.drawable.kr,"سيول"),
    Country("kp","كوريا الشمالية",R.drawable.kp,"بيونغ يانغ"),
    Country("cr","كوستاريكا",R.drawable.cr,"سان خوسيه"),
    Country("co","كولومبيا",R.drawable.co,"بوغوتا"),
    Country("ki","كيريباتي",R.drawable.ki,"ساوث تاراوا"),
    Country("ke","كينيا",R.drawable.ke,"نيروبي"),
    Country("lv","لاتفيا",R.drawable.lv,"ريغا"),
    Country("la","لاوس",R.drawable.la,"فيينتيان"),
    Country("lb","لبنان",R.drawable.lb,"بيروت"),
    Country("lu","لوكسمبورج",R.drawable.lu,"لوكسمبورغ"),
    Country("ly","ليبيا",R.drawable.ly,"طرابلس"),
    Country("lr","ليبيريا",R.drawable.lr,"مونروفيا"),
    Country("lt","ليتوانيا",R.drawable.lt,"فيلنيوس"),
    Country("li","ليختنشتاين",R.drawable.li,"فادوتس"),
    Country("ls","ليسوتو",R.drawable.ls,"ماسيرو"),
    Country("mq","مارتينيك",R.drawable.mq,"فورت دو فرانس"),
    Country("mo","ماكاو الصينية",R.drawable.mo,"ماكاو"),
    Country("mt","مالطا",R.drawable.mt,"فاليتا"),
    Country("ml","مالي",R.drawable.ml,"باماكو"),
    Country("my","ماليزيا",R.drawable.my,"كوالالمبور"),
    Country("yt","مايوت",R.drawable.yt,"مامودزو"),
    Country("mg","مدغشقر",R.drawable.mg,"أنتاناناريفو"),
    Country("eg","مصر",R.drawable.eg,"القاهرة"),
    Country("mk","مقدونيا",R.drawable.mk,"سكوبيه"),
    Country("mw","ملاوي",R.drawable.mw,"ليلونغوي"),
    Country("mn","منغوليا",R.drawable.mn,"أولان باتور"),
    Country("mr","موريتانيا",R.drawable.mr,"نواكشوط"),
    Country("mu","موريشيوس",R.drawable.mu,"بورت لويس"),
    Country("mz","موزمبيق",R.drawable.mz,"مابوتو"),
    Country("md","مولدافيا",R.drawable.md,"كشيناو"),
    Country("mc","موناكو",R.drawable.mc,"موناكو"),
    Country("ms","مونتسرات",R.drawable.ms,"بريدز"),
    Country("mm","ميانمار",R.drawable.mm,"نايبيداو"),
    Country("fm","ميكرونيزيا",R.drawable.fm,"باليكير"),
    Country("na","ناميبيا",R.drawable.na,"ويندهوك"),
    Country("nr","نورو",R.drawable.nr,"يارين"),
    Country("np","نيبال",R.drawable.np,"كاتماندو"),
    Country("ng","نيجيريا",R.drawable.ng,"أبوجا"),
    Country("ni","نيكاراجوا",R.drawable.ni,"ماناغوا"),
    Country("nz","نيوزيلاندا",R.drawable.nz,"ويلينغتون"),
    Country("nu","نيوي",R.drawable.nu,"آلوفي"),
    Country("ht","هايتي",R.drawable.ht,"بورت أو برانس"),
    Country("hn","هندوراس",R.drawable.hn,"تيغوسيغالبا"),
    Country("nl","هولندا",R.drawable.nl,"أمستردام"),
    Country("hk","هونج كونج الصينية",R.drawable.hk,"هونغ كونغ"),
    Country("ss","جنوب السودان",R.drawable.ss,"جوبا"),
    Country("xk","كوسوفو",R.drawable.xk,"بريشتينا"),
)