package com.example.m03_compose

data class Conversation(
    val name: String,
    val lastMessage: String,
    val time: String,
    val profilImage: Int,

)

val conversations = listOf(
    Conversation("Alice", "Hey, how are you?", "10:30 AM", R.drawable.profil1),
    Conversation("Bob", "Let's catch up later.", "9:15 AM", R.drawable.profil2),
    Conversation("Charlie", "Did you see the game last night?", "Yesterday", R.drawable.profil3),
    Conversation("Diana", "Happy Birthday!", "2 days ago", R.drawable.profil4),
    Conversation("Ethan", "Call me when you're free.", "3 days ago", R.drawable.profil5),
    Conversation("Fiona", "Meeting at 5 PM.", "Last week", R.drawable.profil6),
    Conversation("George", "Check out this link.", "Last week", R.drawable.profil7),
    Conversation("Hannah", "See you soon!", "Last month", R.drawable.profil8),
    Conversation("Ian", "Thanks for your help.", "Last month", R.drawable.profil9),
       Conversation("Alice", "Hey, how are you?", "10:30 AM", R.drawable.profil1),
    Conversation("Bob", "Let's catch up later.", "9:15 AM", R.drawable.profil2),
    Conversation("Charlie", "Did you see the game last night?", "Yesterday", R.drawable.profil3),
    Conversation("Diana", "Happy Birthday!", "2 days ago", R.drawable.profil4),
    Conversation("Ethan", "Call me when you're free.", "3 days ago", R.drawable.profil5),
    Conversation("Fiona", "Meeting at 5 PM.", "Last week", R.drawable.profil6),
    Conversation("George", "Check out this link.", "Last week", R.drawable.profil7),
    Conversation("Hannah", "See you soon!", "Last month", R.drawable.profil8),
    Conversation("Ian", "Thanks for your help.", "Last month", R.drawable.profil9),
       Conversation("Alice", "Hey, how are you?", "10:30 AM", R.drawable.profil1),
    Conversation("Bob", "Let's catch up later.", "9:15 AM", R.drawable.profil2),
    Conversation("Charlie", "Did you see the game last night?", "Yesterday", R.drawable.profil3),
    Conversation("Diana", "Happy Birthday!", "2 days ago", R.drawable.profil4),
    Conversation("Ethan", "Call me when you're free.", "3 days ago", R.drawable.profil5),
    Conversation("Fiona", "Meeting at 5 PM.", "Last week", R.drawable.profil6),
    Conversation("George", "Check out this link.", "Last week", R.drawable.profil7),
    Conversation("Hannah", "See you soon!", "Last month", R.drawable.profil8),
    Conversation("Ian", "Thanks for your help.", "Last month", R.drawable.profil9),
       Conversation("Alice", "Hey, how are you?", "10:30 AM", R.drawable.profil1),
    Conversation("Bob", "Let's catch up later.", "9:15 AM", R.drawable.profil2),
    Conversation("Charlie", "Did you see the game last night?", "Yesterday", R.drawable.profil3),
    Conversation("Diana", "Happy Birthday!", "2 days ago", R.drawable.profil4),
    Conversation("Ethan", "Call me when you're free.", "3 days ago", R.drawable.profil5),
    Conversation("Fiona", "Meeting at 5 PM.", "Last week", R.drawable.profil6),
    Conversation("George", "Check out this link.", "Last week", R.drawable.profil7),
    Conversation("Hannah", "See you soon!", "Last month", R.drawable.profil8),
    Conversation("Ian", "Thanks for your help.", "Last month", R.drawable.profil9),
       Conversation("Alice", "Hey, how are you?", "10:30 AM", R.drawable.profil1),
    Conversation("Bob", "Let's catch up later.", "9:15 AM", R.drawable.profil2),
    Conversation("Charlie", "Did you see the game last night?", "Yesterday", R.drawable.profil3),
    Conversation("Diana", "Happy Birthday!", "2 days ago", R.drawable.profil4),
    Conversation("Ethan", "Call me when you're free.", "3 days ago", R.drawable.profil5),
    Conversation("Fiona", "Meeting at 5 PM.", "Last week", R.drawable.profil6),
    Conversation("George", "Check out this link.", "Last week", R.drawable.profil7),
    Conversation("Hannah", "See you soon!", "Last month", R.drawable.profil8),
    Conversation("Ian", "Thanks for your help.", "Last month", R.drawable.profil9),

)